boostorg/context

src/windows/stack_traits.cpp

Some typo or mistake introduced while resolving merge conclicts.maybe. This breaks windows compilation only.

Remove extra "e" in include directive.

---

build/Jamfile.v2
src/asm/jump_i386_ms_pe_masm.asm
src/asm/jump_x86_64_ms_pe_masm.asm
src/asm/make_i386_ms_pe_masm.asm
src/asm/make_x86_64_ms_pe_masm.asm

Symbols incorrectly marked for export on static libraries exported on final executable. This change make symbols not to be marked as export on static builds.

Do not export symbols for static build on PE builds.

---

doc/context.xml
doc/fcontext.qbk
doc/html/context/context.html
doc/html/context/econtext/rationale.html
doc/html/context/rationale.html
doc/rationale.qbk

Nothing major, just typos. I used `grep` and manual replacement to fix duplicate typos. These typos were spotted while reading the Boost.Coroutine doc; see this PR: https://github.com/boostorg/coroutine/pull/22
I don't think that I'll spot more typos soon. If I do, I'll behave like the Nagle's algorithm and will *not* open another pull request.

Fix several typos I spotted while reading the documentation

---

include/boost/context/posix/protected_fixedsize_stack.hpp
include/boost/context/windows/protected_fixedsize_stack.hpp

I created this using find, grep, and sed. No manual editing, but lots of manual inspection. I'm pretty sure that this is correct, and I'm currently running all regression tests. I'll follow up on whether they are successful or not, but just wanted to provide grounds for discussion for https://github.com/boostorg/coroutine/issues/23 .

Fix signed pointer comparison.

---

src/asm/jump_i386_ms_pe_gas.asm
src/asm/jump_x86_64_ms_pe_gas.asm
src/asm/make_i386_ms_pe_gas.asm
src/asm/make_x86_64_ms_pe_gas.asm

fixes #16, the first part of the fedora patch to force platform detection is not needed as it can be overriden from b2 arguments

Fix {make,jump}_fcontext visibility with mingw

---

build/Jamfile.v2

Linking boost.thread is unnecessary if the std library supports std::call_once.
Tested: Fedora Rawhide x86_64 / GCC 6.0.0 20160201

Don't link boost.thread if <mutex> is available.

---

src/posix/stack_traits.cpp
src/windows/stack_traits.cpp

The initial value is required to be BOOST_ONCE_INIT. Luckily, it is currently equivalent to zero, that's why it worked before.

Fix boost::once_flag initialization

---

build/Jamfile.v2
build/cxx11_hdr_mutex.cpp

In some cases it doesn't respect config macros.
I believe this PR will fix build problem reported on devel ML but I can't test because I have no Mac (or similar environment).
Any comments and test results are welcome.

Don't use Boost.Config build-time configure target.

---

include/boost/context/detail/apply.hpp

invoke() could resolve to both boost::context::detail::invoke and std::invoke
because of ADL, which would result in an ambiguous call error
This patch was tested on debian unstable, with gcc 6.2 and clang 3.9. Also, I didn't test the patch in this repository but directly on boost 1.61, but it should be safe enough.

Fix compilation in c++1z

---

include/boost/context/execution_context_v2.hpp
src/asm/make_x86_64_sysv_macho_gas.S

The problem was a wrong type cast and tuple extracting for pointer to transfered data tuples in record::run().

Fix für #38

---

test/test_callcc.cpp
test/test_execution_context_v2.impl

A few tests designed to deliberately fail appeal to UB (undefined
behavior), but as the MSVC optimizer improves we will take advantage of
that to remove UB statements. In order for deliberate failures to occur,
the tests must have the optimizer turned off.

Deliberate-failure tests shouldn't be optimized

---

src/asm/make_arm_aapcs_elf_gas.S

Commit 53e44f632d832f5ccb619c1998d913fba87d94c0 changed "60" to "128" when otherwise adding 64 bytes in make_arm_aapcs_elf_gas.S.  The result of this is that the resulting stack is 4-byte aligned, not 8-byte.  The most notable result of this is that varargs is broken, which pretty much breaks all formatted printing, especially of floats.

Fix stack alignment on arm32-elf

---

src/asm/jump_ppc64_sysv_elf_gas.S
src/asm/make_ppc64_sysv_elf_gas.S
src/asm/ontop_ppc64_sysv_elf_gas.S
test/test_fcontext.cpp

Fixes bugs in the `fcontext` assembly functions for the ppc64/sysv/elf platform.
See issue #50 for more details.
This patch was tested against the latest `develop` commit (a429ff6301) using GCC 5.4 on a POWER7 machine running RHEL 6.6. However, I am not at all familiar with the Boost built/test system, so I am not entirely confident that I ran the unit tests correctly. I ran the following command from the Boost project root directory:
./b2 cxxflags="-std=c++11" --build-dir="/tmp/nick/boost/build" --with-context libs/context/test
The tests ran and failed on the first test without the patch, and then several tests ran and all passed after applying the patch. I think that means the patch works correctly (as far as the functionality covered by those tests goes anyway). Note that since my …

Fix assembly for fcontext on ppc64/sysv/elf

---

src/asm/jump_ppc64_sysv_elf_gas.S
src/asm/make_ppc64_sysv_elf_gas.S
src/asm/ontop_ppc64_sysv_elf_gas.S

I was able to set up some PowerPC virtual machines using QEMU, and I tested the previous patch on ppc (32-bit), ppc64 big-endian (ELFv1), and ppc64 little-endian (ELFv2). The previous patch didn't work with ELFv2 (significant ABI differences from ELFv1). This version was tested and passes the unit tests on all three of the virtual machines mentioned above, although I was only able to run the fcontext test on the 32-bit ppc target since I was using an older version of GCC.

Fix register usage for ppc64/sysv/elfv2

---

include/boost/context/continuation.hpp

Fixes the resolution issue discussed in #52 and #54 that caused compiler errors when using g++-4.9. Also fixes a bad cast that was causing bad values to be passed as arguments into continuations.

Fix callcc functionality for g++-4.9

---

src/asm/jump_i386_sysv_macho_gas.S
src/asm/make_i386_sysv_macho_gas.S
src/asm/ontop_i386_sysv_macho_gas.S

The OSX 32bit ABI differs from the System V ABI in that 8 byte structs
are returned in registers EAX/EDX instead of passing the address of the
struct on the stack. See: https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/LowLevelABI/130-IA-32_Function_Calling_Conventions/IA32.html
The current implementation for this platform crashes when compiled for
32bit OSX (e.g. when running a 32bit iOS simulator) due to not
satisfying the ABI.

Fix i386/macho routines to correctly return transfer_t in EAX/EDX

---

include/boost/context/continuation_fcontext.hpp
include/boost/context/continuation_ucontext.hpp
include/boost/context/continuation_winfib.hpp
include/boost/context/execution_context_v1.hpp
include/boost/context/execution_context_v2.hpp
include/boost/context/execution_context_v2_void.ipp

In a project of mine I have a non-copyable StackAlloc-type. I changed StackAlloc to use perfect forwarding so that it can be moved instead of copied.

use perfect forwarding for StackAlloc

---

src/execution_context.cpp

When BOOST_NO_CXX11_THREAD_LOCAL is defined.

Fix braces in execution_context.cpp

---

build/Jamfile.v2

Turn duplicate sysv-power-32-elf-clang alias into missing sysv-power-32-elf-gcc alias

Duplicate alias should be missing GCC alias

---

include/boost/context/fiber_fcontext.hpp
test/test_fiber.cpp

- fix a cast from `void*` to the wrong dynamic type. The code cast from
`tuple<decay_t<Fn>>*` -> `void*` -> `tuple<Fn>*`, which worked when an rvalue
was passed to resume_with(), but broke if the function was passed
by lvalue-reference, because it resulted in a cast from `Fn` to `Fn&`.
- remove use of `std::tuple` - no need to instantiate it for every callable.

Fix bad static_cast in resume_with:

---

include/boost/context/stack_context.hpp

Fixes a dll-interface warning in MSVC.

Add missing BOST_CONTEXT_DECL in stack_context

---

src/asm/jump_i386_sysv_macho_gas.S

I'm running into crashes on 32bit iOS devices caused by the x87 FPU control word not being saved correctly.
I'm not familiar with the boost.context implementation, but it seems this line is overwriting the control word right before it is loaded.
I think the macho code may have been modeled after the elf version,
which writes the returned transport_t through a pointer in eax,
however macho is expected to return its transport_t result in eax:edx.
The macho code mistakenly wrote its "data" return value through eax.
This happens to overwrite the saved fc_x87_cw before it is loaded,
resulting in floating-point exceptions and crashes in unrelated code.
Does that sound about right?

Fix jump_i386_sysv_macho writing garbage to the x87 control word

---

src/asm/ontop_ppc64_sysv_elf_gas.S

The existing ontop_fcontext implementation for ppc64 ELFv2
violates the ABI by not storing the callback entry address
in %r12 before branching. This results in crashes on this
platform.
This commit addresses this and allows the context library
to function as expected on ppc64 platforms using the ELFv2 ABI.
The OpenPOWER ELFv2 ABI states on page 41, section 2.2.1.1: "r12 [...] Function entry address at the global entry point."

Fix ABI violation on ppc64 ELFv2, fixes #72

---

build/Jamfile.v2
build/architecture.jam
src/asm/jump_s390x_sysv_elf_gas.S
src/asm/make_s390x_sysv_elf_gas.S
src/asm/ontop_s390x_sysv_elf_gas.S

This adds the support for S390x ARCH.
Tests have been run and they all pass.

S390x: Add Support for s390x arch

---

src/asm/jump_s390x_sysv_elf_gas.S
src/asm/make_s390x_sysv_elf_gas.S
src/asm/ontop_s390x_sysv_elf_gas.S

Some optimizations for the s390x implementation of jump/make/ontop:
- Use multiple register instructions rather than individual load/stores
- Use floating point instructions to load or store from/to storage
- Use symbols to map CTX rather than explicit displacements
- Branch to _exit@PLT to avoid relocation complaints
- Use immediate instructions for adding to registers
Builds and passes fcontext tests using gcc-4.8.5 and devtoolset-8-gcc-c++ (8.3.1).
Do you need access to a jenkins worker so you can build/test s390x automatically?

Optimize s390x instructions

---

include/boost/context/detail/config.hpp
include/boost/context/fixedsize_stack.hpp
include/boost/context/pooled_fixedsize_stack.hpp
include/boost/context/posix/protected_fixedsize_stack.hpp
test/Jamfile.v2

Since OpenBSD 6.4 (https://www.openbsd.org/64.html), the stack pointer
must point to MAP_STACK memory, or the kernel may kill the process
with a signal.  All stack allocators must pass MAP_STACK to mmap(2).
Define BOOST_CONTEXT_USE_MAP_STACK on OpenBSD, and don't define it on
other systems.  This doesn't check for old versions of OpenBSD without
MAP_STACK; but OpenBSD has stopped maintaining versions before 6.4.
If BOOST_CONTEXT_USE_MAP_STACK is defined, then cause the stack
allocators to pass MAP_STACK to mmap(2):
- fixedsize_stack uses mmap/munmap instead of malloc/free.  This
comes from a patch in OpenBSD Ports.
- protected_fixedsize_stack adds MAP_STACK to the mmap flags (as it
does in OpenBSD Ports).  Assume that systems with MAP_STACK also
have MAP_ANON; this is true on OpenBSD. …

Use mmap(2) MAP_STACK to allocate stacks on OpenBSD

---

include/boost/context/detail/prefetch.hpp

Much like https://github.com/boostorg/type_traits/pull/106, only allow
x86-specific intrinsics when targetting x86-like architectures.

Fix compilation with MSVC for ARM

---

src/asm/jump_i386_ms_pe_gas.asm
src/asm/make_i386_ms_pe_gas.asm
src/asm/ontop_i386_ms_pe_gas.asm

The incorrect exports can cause linker issues (at least when using LLVM's lld-link) claiming that these primitives are not available.

Fix exports for 32-bit GNU assembler files targeting Windows.

---

src/asm/jump_i386_ms_pe_gas.asm
src/asm/make_i386_ms_pe_gas.asm
src/asm/ontop_i386_ms_pe_gas.asm

We set the LSB of the magic symbol @feat.00 to 1. This symbol is used for compiler-linker communication, and the LSB expresses that an object file has opted into "safeseh"; any SEH handlers used in this file must be listed in the .sxdata section.
Since we don't register any SEH handlers in these files, this is trivially satisfied.
Reference: [the PE-COFF specification](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#the-sxdata-section).

Mark 32-bit GNU assembly files targeting Windows as safeseh compatible

---

src/asm/make_riscv64_sysv_elf_gas.S

Since this ends up in a shared library we should use a PLT call.  Also,
the finish label is local, so we can use lla instead of la.

Fix non-PIC in RISC-V assembly

---

build/Jamfile.v2

We should set abi for 64bit as n64, and 32bit for o32.
This patch depends on the patch of boost/build.

Use OSPLAT MIPS32/MIPS64 to set different ABI

---

src/asm/jump_mips64_n64_elf_gas.S
src/asm/make_mips64_n64_elf_gas.S
src/asm/ontop_mips64_n64_elf_gas.S

The right align for mips64/n64 is 3 instead of 2.

mips64/n64: .align 3

---

src/asm/jump_s390x_sysv_elf_gas.S
src/asm/make_s390x_sysv_elf_gas.S
src/asm/ontop_s390x_sysv_elf_gas.S

I found the current IBM Z fcontext support being broken and propose the following implementation instead.
Problems with the existing implementation:
1. jump_fcontext returns the wrong context pointer. Instead of returning the address of the saved context it returns the current stack pointer. Interestingly this makes the testsuite to always exit early with exit code 0. The second jump_fcontext always jumps to the exit stub set up in make_fcontext.
2. The address of the hidden return slot needs to be saved as part of the context otherwise. Using the return slot of the current jump_fcontext invocation is wrong.
3. The wrong FP registers are being saved and FPC is missing. The call-saved FP regs on IBM Z 64 bit are f8-f15. The current code saves f1, f3, f5, f7.
A few details about the …

IBM Z: Fix fcontext routines

---

build/Jamfile.v2
test/Jamfile.v2

PR related to https://github.com/boostorg/context/issues/143 issue.
Flag -fsplit-stack is only available on Linux according error message and documentation.

-fsplit-stack flag with GCC

---

src/asm/jump_x86_64_sysv_elf_gas.S
src/asm/ontop_x86_64_sysv_elf_gas.S

In the x32 ABI, pointers take up 4 bytes, so a structure containing two pointers is passed and returned in a single 8-byte register.
Changes required to build for the x32 ABI in the first place are not part of this pull request: that is the subject of https://github.com/boostorg/build/issues/388. I have tested this PR on top of local modifications that bypass Boost's forced overriding of compiler flags.

Fixes for x32 ABI.

---

src/asm/jump_i386_ms_pe_gas.asm
src/asm/make_i386_ms_pe_gas.asm
src/asm/ontop_i386_ms_pe_gas.asm

This reverts 85783e8, as the wrong linker was used
Closes #136

Revert "Fix exports for 32-bit GNU assembler files targeting Windows."

---

include/boost/context/detail/config.hpp

Crash otherwise.
I haven't tried winfibers.
I think this should fix https://github.com/boostorg/coroutine2/issues/34. Is this the kind of patch that could get in? Or how else?

In cygwin we want to use UCONTEXT

---

src/asm/jump_mips64_n64_elf_gas.S
src/asm/ontop_mips64_n64_elf_gas.S

Added define also found in the MIPS32 ASM files.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

fix softfloat support for MIPS64 ASM

---

src/asm/jump_combined_sysv_macho_gas.S
src/asm/make_combined_sysv_macho_gas.S
src/asm/ontop_combined_sysv_macho_gas.S

Apple silicon M1 uses arm64 architecture, this commit will add arm and arm64 architecture into combined asm code in order to support newer apple's machine in combined asm codes.

Add arm and arm64 into combined asm codes

---

include/boost/context/posix/protected_fixedsize_stack.hpp
include/boost/context/windows/protected_fixedsize_stack.hpp

The previous math can go wrong if size_ cannot be exactly expressed with fp32.

Use integer math instead of floating-point to compute number of pages

---

build/Jamfile.v2

Closes https://github.com/boostorg/context/issues/177

Allow building asm_sources with GCC on 64-bit MACH-O

---

src/asm/jump_ppc64_sysv_xcoff_gas.S
src/asm/make_ppc64_sysv_xcoff_gas.S

It should almost exactly match the ELFv1 ABI code now, except with IBM assembler syntax.
Tested with [PHP fibres](https://github.com/php/php-src/pull/7338). Fixes #180

Fix 64-bit XCOFF assembly

---

CMakeLists.txt

Without this, asm files passed to gcc with "-c" option (without preprocessing).
It leads to the following warnings and error:
```log
[  7%] Building ASM object libs/context/CMakeFiles/boost_context.dir/src/asm/make_x86_64_ms_pe_gas.asm.obj
gcc.exe: warning: C:\boost\libs\context\src\asm\make_x86_64_ms_pe_gas.asm: linker input file unused because linking not done
[  7%] Building ASM object libs/context/CMakeFiles/boost_context.dir/src/asm/jump_x86_64_ms_pe_gas.asm.obj
gcc.exe: warning: C:\boost\libs\context\src\asm\jump_x86_64_ms_pe_gas.asm: linker input file unused because linking not done
[  8%] Building ASM object libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_x86_64_ms_pe_gas.asm.obj
gcc.exe: warning: C:\boost\libs\context\src\asm\ontop_x86_64_ms_pe_gas.asm: linker input file …
```

Fix build with cmake and gcc

---

src/asm/jump_arm_aapcs_macho_gas.S
src/asm/ontop_arm_aapcs_macho_gas.S

I've found this fix in our codebase. Not sure how it works, but my guess is following:
`__PTK_LIBC_DYLD_Unwind_SjLj_Key` is defined in https://opensource.apple.com/source/libpthread/libpthread-137.1.1/private/tsd_private.h as `#define __PTK_LIBC_DYLD_Unwind_SjLj_Key	18`. Multiplying it on a size of a pointer gives `72`.
P.S.: it already was `72` before https://github.com/boostorg/context/commit/763f28542d3c2931ead6eef1409b113155e9a1c9

restore work with TLS[__PTK_LIBC_DYLD_Unwind_SjLj_Key] on arm aapcs macho

---

build/Jamfile.v2

Tested on OpenBSD -current riscv64 with Clang 11.1.0.

Add support for building on riscv64 with Clang

---

src/asm/jump_x86_64_sysv_elf_gas.S
src/asm/make_x86_64_sysv_elf_gas.S
src/asm/ontop_x86_64_sysv_elf_gas.S

Indirect Branch Tracking(IBT) is part of Intel's Control-Flow
Enforcement Technology(CET). IBT is hardware based, forward edge
Control-Flow-Integrity mechanism where any indirect CALL/JMP must
target an ENDBR instruction or suffer #CP.
This commit inserts endbr64 instruction in assembly to support IBT.
Signed-off-by: PeterYang12 <yuhan.yang@intel.com>
Signed-off-by: Chen, Hu <hu1.chen@intel.com>

Add support for Indirect Branch Tracking (IBT)

---

.github/workflows/multi.yml
test/Jamfile.v2
test/is_libstdcxx.cpp
test/test_apply.cpp
test/test_callcc.cpp
test/test_fcontext.cpp
test/test_fiber.cpp
test/test_invoke.cpp

Run tests on most of supported platforms via QEMU. There seems to be no distro that supports powerpc, debian jessie packages for powerpc are no longer available.
Some changes I had to make:
- Run segmented stack tests only when compiler has `-fsplit-stack` and targeted libstdc++ (adds Clang, limits on unsupported arches and stdlibs).
- Switch to lightweight tester from Boost.Test. It was failing mingw for some reason, and this also speed up qemu runners at least x2 (ppc64el 28mins vs 11mins).

CI: Test multiple architectures

---

src/asm/make_ppc32_sysv_macho_gas.S

Minor but needed fix to Darwin ppc32 code: https://github.com/boostorg/context/pull/204#issuecomment-1270061890
Builds fine on 10.5.8, 10.6 PPC (10A190) and 10.6.8 Rosetta.
Functionality: just built `folly` (which depends on context/coroutine) on 10.5.8 ppc with it with a bunch of dependents, so apparently all good.
@olk Hopefully we are done at this, and Darwin PPC will finally work. Once merged here, I will bring it to Macports.

Darwin make_ppc32: fix addi in l1

---

include/boost/context/continuation_ucontext.hpp
include/boost/context/fiber_ucontext.hpp

1. MacOS version of ::makecontext (tested on m1 Mac Ventura 13.0.1) is able to pass only 4-byte parameters to context function
2. define _XOPEN_SOURCE before inclusion of predef.h
https://github.com/boostorg/context/issues/184

fix ucontext for MacOS

---

src/asm/make_i386_sysv_elf_gas.S
src/asm/make_i386_sysv_macho_gas.S

SysV ABI requires a stack alignment of 16 bytes. Currently, for i386 with SysV ABI, the trampoline function is entered with an unaligned stack. This causes problems for the context-function that is jumped to as its stack is also unaligned. This causes a crash for our use-case because the context function contains an SSE instruction which reads from the stack. The SSE instruction requires the correct alignment. Fix it by changing the 0x2c offset to 0x30, such that the stack remains aligned.
Related issue in this repo: #210 
For reference:
https://github.com/php/php-src/pull/10407#issuecomment-1404180877 and https://github.com/php/php-src/issues/10398

Make sure the i386 sysv stack is aligned

---

src/asm/jump_s390x_sysv_elf_gas.S
src/asm/make_s390x_sysv_elf_gas.S
src/asm/ontop_s390x_sysv_elf_gas.S

In the current implementation fibres spawned by other fibres or threads would have the argument of their entry point (`void fiber_entry( transfer_t t)`) be allocated on the stack of their parent, which would then cause segmentation fault if the former outlived the latter.
The x86-64 implementation (`x86_64_sysv_elf` is the combination I tested) supports this use-case, so this change means to achieve feature parity for the s390x implementation in this regard by storing the aforementioned argument in the fibre's own stack.

Store entry point arguments in fibre's own stack (s390x)

---

build/Jamfile.v2

@olk Bring consistency there, add `gcc`. (In fact, presently `clang` is broken on macOS ppc, but let it be there, maybe it gets fixed some day.)

Jamfile: sort out macOS ppc asm_sources

---

src/asm/jump_s390x_sysv_elf_gas.S
src/asm/make_s390x_sysv_elf_gas.S
src/asm/ontop_s390x_sysv_elf_gas.S

I implemented review comments by @Andreas-Krebbel from #224. I ran the tests using `b2` (`../../../b2 -a`) and everything seems to be passing.

Improve ABI conformance of s390x fcontext

---

build/Jamfile.v2

`in` operator in bjam always returns true if its first argument has no elements[1]. This means that if `os.platform` is empty (not detected), the construction introduced in commit d039c8e4da79dbc76481236249e22892bfdde047 sets ABI to `aapcs` on all platforms where `os.platform` is empty, including, e.g. riscv64, and breaks build there.
This commit refactors the condition to use '=' operator, to make sure that when `os.platform` is empty we get the default ABI value, and thus fixes build on riscv64.
[1] https://www.boost.org/doc/libs/1_83_0/tools/build/doc/html/index.html#jam.language.flow_of_control
Fixes: d039c8e4da79dbc76481236249e22892bfdde047

Fix ABI detection for empty 'os.platform'

---

include/boost/context/continuation_ucontext.hpp
include/boost/context/fiber_ucontext.hpp

BOOST_OS_MACOS is always defined; when we're not compiling for Mac OS, it's just defined as zero. So, the correct check is `#if BOOST_OS_MACOS`, because `#ifdef BOOST_OS_MACOS` is true on any operating system.
Fixes: cc106be672f54b71842aa6322fe45bf60ed1d3cc
Reported-by: Ilya Kurdyukov <ilyakurdyukov@altlinux.org>

Fix check for BOOST_OS_MACOS

---

CMakeLists.txt

Adjust compile definitions to adhere to KEY=VALUE (where VALUE is empty string) so it builds with qcc. Closes #239

CMake: Fix assembler `--defsym` format issue (qcc/qnx)

---

src/posix/stack_traits.cpp

Casting them out will fix the problem easily. I'm also gonna open a pull request for [Boost::coroutine](https://github.com/boostorg/coroutine/tree/develop) warnings as well.
g++ (GCC) 13.2.1 20230801
```c++
[17/27] Building CXX object _deps/boost_context-build/CMakeFiles/boost_context.dir/src/posix/stack_traits.cpp.o
/webpp/build-dev-clang/_deps/boost_context-src/src/posix/stack_traits.cpp:42:12: warning: implicit conversion changes signedness: 'long' to 'std::size_t' (aka 'unsigned long') [-Wsign-conversion]
return ::sysconf( _SC_PAGESIZE);
~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~
/webpp/build-dev-clang/_deps/boost_context-src/src/posix/stack_traits.cpp:80:12: warning: implicit conversion changes signedness: 'long' to 'std::size_t' (aka 'unsigned long') [-Wsign-conversion]
return MINSIGSTKSZ; …
```

Suppressing -Wsign-conversion warnings

---

src/asm/jump_x86_64_sysv_elf_gas.S
src/asm/make_x86_64_sysv_elf_gas.S

on those platforms, albeit being 64 bits, they produce 32 bits binaries by default.

fix solaris/illumos build on make/jump assembly directives.

---

build/Jamfile.v2
src/asm/jump_sparc64_sysv_elf_gas.S
src/asm/make_sparc64_sysv_elf_gas.S
src/asm/ontop_sparc64_sysv_elf_gas.S

This implements the required asm functions for sparc64_sysv_elf and was tested on an OpenBSD/sparc64 system.
Jump_fcontext uses an extra C call frame to store the frame-pointer and return address. Because of this the code is simply a save (to new reg window), then forcing a window flush and finally switch stack and restore from there.
Since jump_fcontext() uses a register window and stack frame, make_fcontext() reserves two call frames on the stack (one for jump_fcontext() and the other for the callback function).
OpenBSD/sparc64 uses stackghost which prevents userland from overriding the return-address on the stack because of this make_fcontext() uses an extra trampoline to implement the _exit(0) call if the callback returns.
All tests pass with this on OpenBSD/sparc64 (also the tests …

Implement the fcontext asm for sparc64

---

build/Jamfile.v2
src/asm/jump_arm64_aapcs_pe_armclang.S
src/asm/make_arm64_aapcs_pe_armclang.S
src/asm/ontop_arm64_aapcs_pe_armclang.S

The armasm legacy assembler is deprecated. The code was migrated to the GNU syntax (used by armclang).
https://developer.arm.com/documentation/100068/0621/Migrating-from-armasm-to-the-armclang-Integrated-Assembler
Split this into two commit to keep the history and diff clean

Convert ARM64 armasm to armclang

---

src/asm/jump_x86_64_sysv_elf_gas.S
src/asm/make_x86_64_sysv_elf_gas.S

This fixes accidental duplication introduced in https://github.com/boostorg/context/pull/248

Remove accidentally duplicated shadow stack handling

---

CMakeLists.txt

There is a problem on visual studio to compile Boost::context with BOOST_CONTEXT_IMPLEMENTATION = "fcontext".
For all asm files are no build tool defined so they will not be compiled during build of context lib and functions "jump_fcontext, make_fcontext and ontop_fcontext" are no compiled.
The fix is to pass the defined ASM_LANGUAGE on each asm file as PROPERTY.

fix for for: visual studio missing buildtool peroperty for asm files

---

include/boost/context/fiber_fcontext.hpp

`__NR_map_shadow_stack` is defined to 453 (not 451) on Ubuntu 24.04 with Linux kernel 6.8.0-44, gcc 13.2.0 and glibc 2.39. This causes warnings about macro redefinition when Boost.Fiber is compiled.
Change the syscall number to 453 and only define the macro if it has not been defined already. Also include `unistd.h` for `syscall()` and `__NR_*` constants.
Also convert tabs to spaces and trim trailing spaces.
Fixes https://github.com/boostorg/context/issues/263.
Fixes https://github.com/boostorg/context/issues/269.

Fix shadowstack syscall number redefinition

---

build/Jamfile.v2

Adds a definition which assembler files should be used for ARM64 + Windows + GCC combination. (This is needed for a new target `aarch64-w64-mingw32` for MinGW which is being developed here: https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build)
It is enough to use the existing assembler for Clang on Arm64 (introduced here https://github.com/boostorg/context/pull/262) as they both use the GNU syntax.
Also the first commit fixes the assembler extensions for Clang.

Define assembler files for ARM64 + Windows + GCC combination

---

CMakeLists.txt

We used to build boost-context on MSYS2/clangarm64 (https://github.com/msys2/MINGW-packages/commit/da4f4c37).

Support building assembly files for mingw-w64 on arm64 with CMake.

---

include/boost/context/fiber_fcontext.hpp

This completes https://github.com/boostorg/context/pull/285

Suppressed unused variable warning in fiber_fcontext.hpp

---

src/asm/make_x86_64_sysv_elf_gas.S

Hello! I find mistake at code under BOOST_CONTEXT_TLS_STACK_PROTECTOR for x86_64.

fix tls stack protector on x86_64

---

CMakeLists.txt

PR for #293
Put `if (GNU/Clang)` into the MASM's `else` clause since `Clang-CL` validates positive at `CMAKE_CXX_COMPILER_ID STREQUAL "Clang"` while also having `MSVC` frontend for compile options and utilising `ML` masm assembler.
UPD: `clang-cl` `/quiet` support has been dropped due to [inability to know real version for sure](https://github.com/boostorg/context/issues/293#issuecomment-2676320713).
Side (weird) _fix_ for `/quiet` flag being passed on `MSVC_VERSION: 1936` despite Visual Studio Enterprise 2019 **Version 16.11.35**:
<details><summary>Dropping context</summary>
- Visual Studio Enterprise 2019 **Version 16.11.35**
- (Microsoft (R) Macro Assembler (x64) Version 14.29.30154.0)
- `message(STATUS "MSVC_VERSION: ${MSVC_VERSION}")` = `-- MSVC_VERSION: 1936` …

Fix `clang-cl` `MSVC` frontend received `GNU` flag on assembling

---

build/Jamfile.v2

Parallel to #178 but for aarch64 instead of x86_64

Support gcc when building ASM on Darwin

---

.github/workflows/ci.yml

The Ubuntu 20.04 image on GitHub Actions has been unavailable since 2025-04-15. See <https://github.com/actions/runner-images/issues/11101> for more information on the deprecation and removal.
Therefore all build jobs that use the Ubuntu 20.04 runner image of GHA will fail and have to be replaced or removed.
Also see <https://github.com/boostorg/context/actions/runs/14540788005/job/40798186788> for an example for a failing build on `ubuntu-20.04`. It fails with the error message:
> This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101

Remove Ubuntu 20.04 build from CI

---

include/boost/context/fiber_fcontext.hpp

In the destructor of fiber its context can be loaded. The exception state saved in `resume()`/`resume_with()` can be restored during stack unwinding after a `forced_unwind` exception is thrown, which is caught afterwards, i.e. the exception state becomes corrupted.
This patch ensures that the correct exception state is restored before the destructor of the fiber returns.
Fixes #302.

restore exception state after destruction of fiber

---

src/asm/jump_arm64_aapcs_elf_gas.S
src/asm/make_arm64_aapcs_elf_gas.S
src/asm/ontop_arm64_aapcs_elf_gas.S

**Add BTI hint + GNU property to fcontext trampolines** 
The AArch64 fcontext trampolines (jump_fcontext, make_fcontext, ontop_fcontext) are indirect-entry-points. On BTI-enforcing systems they must begin with a BTI or the first resume can trap with SIGILL.
Insert `bti c` (hint #34) at each entry under `__ARM_FEATURE_BTI_DEFAULT`, and emit `GNU_PROPERTY_AARCH64_FEATURE_1_BTI` from each AArch64 assembly file so linkers map the DSO with PROT_BTI.
Scope: ELF/GAS AArch64 trampolines only; +4 bytes per entry
Fixes [#308](https://github.com/boostorg/context/issues/308)
Notes
- This change is orthogonal to the separate LLVM landing-pad ``bti j`` [issue #149267](https://github.com/llvm/llvm-project/issues/149267); exception paths built with affected Clang toolchains will still require the …

[AArch64][BTI] Add BTI hint + GNU property to fcontext trampolines 
